services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: next-app
    container_name: nextgeneral-app
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=http://82.112.230.106:8009
    ports:
      - "3068:3068"
    networks:
      - next-general

networks:
  next-general:
    driver: bridge
